name: sally_smart
description: Sally Smart Grocery


version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_barcode_scanner: ^0.1.7
  audioplayers: ^0.13.1
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.4.1
  provider: ^4.0.5
  font_awesome_flutter: ^8.8.1
  rxdart: ^0.24.0
  credit_card_type_detector: ^1.1.0
  flutter_credit_card: ^0.1.3
  square_in_app_payments: ^1.3.0
  get_it: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - assets/barcode_sound.mp3
    - assets/missing_avatar_F.png
    - images/
    - secrets.json


  fonts:
    - family: Cousine
      fonts:
        - asset: fonts/Cousine-Regular.ttf


    - family: SecularOne
      fonts:
        - asset: fonts/SecularOne-Regular.ttf


    - family: Nehama
      fonts:
        - asset: fonts/nehama-webfont.ttf


    - family: Avraham
      fonts:
        - asset: fonts/Abraham-Regular.ttf


