name: sally_smart
description: Sally Smart Grocery


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_barcode_scanner: ^0.1.5
  audioplayers: ^0.13.1





dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - assets/barcode_sound.mp3


  fonts:
    - family: Cousine
      fonts:
        - asset: fonts/Cousine-Regular.ttf


    - family: SecularOne
      fonts:
        - asset: fonts/SecularOne-Regular.ttf



