name: sally_smart
description: Sally Smart Grocery


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_barcode_scanner: ^0.1.5
  audioplayers: ^0.13.1
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0+1
  cloud_firestore: ^0.12.9
  modal_progress_hud: ^0.1.3








dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - assets/barcode_sound.mp3
    - assets/missing_avatar_F.png
    - images/


  fonts:
    - family: Cousine
      fonts:
        - asset: fonts/Cousine-Regular.ttf


    - family: SecularOne
      fonts:
        - asset: fonts/SecularOne-Regular.ttf


    - family: Nehama
      fonts:
        - asset: fonts/nehama-webfont.ttf


    - family: Avraham
      fonts:
        - asset: fonts/Abraham-Regular.ttf


